---
title: "Smug Instation"
output: html_notebook
---

```{r setup, Libraries, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

# Document Creation
library(knitr)
library(markdown)
library(yaml)
library(distill)
library(blogdown)

# Basic Analysis
library(ggplot2)
library(tidyverse)
library(clipr)
library(dbplyr)
library(data.table)
library(stringr)
library(stringi)
library(tibble)
library(tidyr)

# SNA - Social Network Analysis

library(tergm)
library(ergm)
library(network)
library(networkDynamic)
library(networkDynamicData)

library(statnet)
library(igraph)
library(igraphdata)
library(tsna)
library(sna)

```

---

```{r Set Working Directory, include=FALSE}
getwd()

setwd("C:/Users/white/iCloudDrive/Documents/1_DACSS_UMassAmherst/Dacss_RProjects/3. Sp22_rProjects/Dacss_679- Coursework/GIT-ajw_Learning-SocialNetworkAnalysis/docs/3. SNA - Assignments/sna_Week3")


```
##   Project Varriables
    
    Raw Data:
  indx_SmugglerCove_recip

    DataFrame:
  smugCovIdx
            "dnkNam" "ingNam" "dnkIng" "ingTyp"
 
    Matrix:
 
        
    Network Objects: EDGE LIST
  

## Basic R: Import & Clean Data

```{r Read raw data into R}

library(readr)

indx_SmugglerCove_recip <- read_csv("C:/Users/white/iCloudDrive/Documents/1_DACSS_UMassAmherst/Dacss_RProjects/3. Sp22_rProjects/Dacss_679- Coursework/GIT-ajw_Learning-SocialNetworkAnalysis/docs/3. SNA-Data/index-by_name-Smuggler_Cove-cocktail_recipies.csv", 
    col_names = FALSE, 
    col_types = cols(X1 = col_skip(),
                     X4 = col_skip()), 
                    na = "empty")

View(indx_SmugglerCove_recip)
summary(indx_SmugglerCove_recip)

 # Smuggler's Cove

smugCovIdx <- indx_SmugglerCove_recip

```

```{r Getting Information on a Dataset:, echo=FALSE}

# list the structure of smugCovIdx
str(smugCovIdx)

# class of an object (numeric, matrix, data frame, etc)
class(smugCovIdx)

# list the variables in smugCovIdx
names(smugCovIdx)

# dimensions of an object
dim(smugCovIdx)
```

```{r & Clean Data}

  library(stringr)
# DATA Cleaning

      # Drop NA rows
smugCovIdx <- na.omit(smugCovIdx) 

#####
#     Drop it like...
#####
      # DROP COLUMNS FROM DATA FRAME
                      
smugCovIdx = subset(smugCovIdx, 
                       select = -c(4)
                       )

#####

#     Extract variables
#####

          # extract first word of the column, adds values in new Column at the end of DF

                    #1st pastIt
passIt <- smugCovIdx      

colnames(passIt)
                    #2nd passIt
passIt$substring_first <- str_extract(passIt$X5,"(\\w+)") 

#####

#####
#     Give Variables a human name
#####

# rename column names with human language

                      # Return it
colnames(passIt)
smugCovIdx <- passIt

colnames(smugCovIdx)
names(smugCovIdx )[1] <- "dnkNam"
names(smugCovIdx )[2] <- "ingNam"
names(smugCovIdx )[3] <- "dnkIng"
names(smugCovIdx )[4] <- "ingTyp"
colnames(smugCovIdx)
```


## Statnet
```{r STATNET: Smug edgelist}
      # read the data into Code Block

source_df<-smugCovIdx

    #Format DF to become an edgelist

sourceEL <- source_df[
  c( #select column numbers from source.Data in order to be added
   1:4)]

library(statnet)

    #**STATNET** object from edgelist
          # No vertex attribute data
          # No edge attribute data

    #**Create object.**
snEL <- 
  network(as.matrix
          (sourceEL[1:2], 
            matrix.type = 'edgelist'))
                  
#**Assign:**VERTICES atributes <aka colnames>
 
 snEL%v%"dNam"<- sourceEL$dnkNam
 snEL%v%"iNam"<- sourceEL$ingNam
        
              
#**Assign:** edge atributes <aka colnames>        
      
snEL%e%"ingTyp" <- sourceEL$ingTyp
# snEL%e%"dnkNam" <- sourceEL$dnkNam

   
#**Purge* unwanted attributes
          network::delete.vertex.attribute(snEL,"na")
         # network::delete.vertex.attribute(snEL,"vertex.names")
          network::delete.edge.attribute(snEL,"na")
  
  #######**VERIFY**
          network::list.vertex.attributes(snEL)
          network::list.edge.attributes(snEL)
          class(snEL)
          print(snEL)
#
##          
###
###** it's a bloody statnet edgelist !!! **###
```



## igraph
```{r igraph: smug edgelist}
# read the data into Code Block

source_df<-smugCovIdx


    #Format DF to become an edgelist

sourceEL <- source_df[
  c( #select column numbers from source.Data in order to be added
   1:4)]

library(igraph)

#**Create Edgelist Matrix** 

sourceEL_mx = 
            as.matrix(source_df[1:2],
                      matrix.type = "edgelist",
    ##**Note** Var 1 is empty, Var 2 Contains edgelist          
          
          
#**Create igraph object** 
         
igEL <- graph.edgelist(sourceEL_mx, 
                       directed = F)

#**add/remove** edge attribute ...because it's easy...#

E(igEL)$ingTyp<-source_df$ingTyp


   #**create vertex attributes** in igraph
 
set_vertex_attr(igEL,
                name = "dNam",
                value = source_df[c("dnkNam")])
V(igEL)$dNam<-source_df$dnkNam



set_vertex_attr(igEL,
                name = "iNam",
                value = source_df[c("ingNam")])
V(igEL)$iNam<-source_df$ingNam       
 
```

