---
title: "Social Network Analysis: Week 3: Degree and Centrality"
description: " "
author:
  - name: "Audra Jamai White" 
    url: 
    affiliation: "Umass Amherst - DACSS 679: Social Network Analysis"
    affiliation_url: 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, Libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Document Creation
library(knitr)
library(markdown)
library(yaml)
library(distill)
library(blogdown)

# Basic Analysis
library(ggplot2)
library(tidyverse)
library(clipr)
library(dbplyr)
library(data.table)
library(stringr)
library(stringi)
library(tibble)
library(tidyr)

# SNA - Social Network Analysis

library(tergm)
library(ergm)
library(network)
library(networkDynamic)
library(networkDynamicData)

library(statnet)
library(igraph)
library(igraphdata)
library(tsna)
library(sna)

```

#        *Write up your results briefly: *
*   focus on interpretation of the results. 
*   Don’t list statistics or provide code, 
*  **the goal is to choose a few interesting results and provide an interpretation.**

##        *Briefly describe the dataset:*
1.   identify initial network format; 
2.   describe and identify the nodes 
     including: 
        *  how many nodes are in the dataset; 
3.   what constitutes a tie or edge
     including:
        *  how many ties, 
        *   whether ties are directed/undirected,
        *   whether ties are weighted/binary, 
        *   and how to interpret the value of the tie if any.
        *   Whether or not there are edge attributes 
            that might be used to:
            *   subset data, or 
            *   stack multiple networks. 

##        *Provide at least two or three noteworthy results*, including:
1.   the relevant statistics and interpretation. 
        For example, explaining which node(s) are most central and which are least central. 
2.   Discuss (with any related evidence) whether or not the node(s) behavior is in line with or violates expectations based on the degree centrality measure. 
3.   What do you make of network density and centralization measures?  
4.   What about differences in the binary 100 million threshold network vs valued trade flows network. 
 5.  Check tutorial for other ideas of results to discuss.

#  Working from the example R syntax:
1.   calculate network density; 
2.   degree centrality, and 
3.   centralization measures for your network data. 
# Import & Describe Network



# 1.   calculate network density
# 2.   degree centrality
# 3.   centralization measures for your network data. 

# 
> Distill is a publication format for scientific and technical writing, native to the web.
>
> Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.